import type { ColumnType, Generated } from "kysely";

/** A timestamptz column the database fills in. */
type CreatedAt = ColumnType<Date, never, never>;
/** A timestamptz column a trigger keeps current. */
type UpdatedAt = ColumnType<Date, never, never>;

export interface CafesTable {
  id: ColumnType<string, string | undefined, never>;
  name: string;
  time_zone: Generated<string>;
  catalog_version: Generated<number>;
  /** The code in the café's printed signup QR; join_code_hash is its SHA-256, generated by the database. */
  join_code: Generated<string>;
  join_code_hash: ColumnType<Buffer, never, never>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export interface LoyaltyProgramsTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  stamps_required: number;
  reward_name_ar: string;
  reward_name_en: string;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export interface OrderTypesTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  name_ar: string;
  name_en: string;
  price_cents: number;
  cost_cents: number;
  stamps_earned: Generated<number>;
  active: Generated<boolean>;
  sort_order: Generated<number>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type AuditActorType = "owner" | "staff" | "device" | "system";

/** Append-only: the app role may insert and read, never update or delete. `changes` must hold no personal data. */
export interface AuditLogTable {
  id: ColumnType<string, never, never>;
  cafe_id: ColumnType<string, string, never>;
  actor_type: ColumnType<AuditActorType, AuditActorType, never>;
  actor_id: ColumnType<string | null, string | null | undefined, never>;
  action: ColumnType<string, string, never>;
  entity_type: ColumnType<string, string, never>;
  entity_id: ColumnType<string | null, string | null | undefined, never>;
  changes: ColumnType<Record<string, unknown>, string | undefined, never>;
  occurred_at: CreatedAt;
}

/** A token column: the SHA-256 hash of a secret the client holds (32 bytes). */
type TokenHash = ColumnType<Buffer, Buffer, never>;

export interface OwnersTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  /** Lower-case; unique across every café. */
  email: ColumnType<string, string, never>;
  password_hash: string;
  password_changed_at: ColumnType<Date, Date | undefined, Date>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export interface OwnerInvitesTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  token_hash: TokenHash;
  expires_at: ColumnType<Date, Date, never>;
  used_at: ColumnType<Date | null, never, Date>;
  created_at: CreatedAt;
}

export interface OwnerSessionsTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  owner_id: ColumnType<string, string, never>;
  token_hash: TokenHash;
  created_at: CreatedAt;
  last_seen_at: ColumnType<Date, never, Date>;
  expires_at: ColumnType<Date, Date, never>;
}

export interface PasswordResetTokensTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  owner_id: ColumnType<string, string, never>;
  token_hash: TokenHash;
  expires_at: ColumnType<Date, Date, never>;
  created_at: CreatedAt;
}

export interface StaffTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  name: string;
  /** PBKDF2-SHA256 of the PIN: 16-byte salt, 32-byte hash. */
  pin_salt: ColumnType<Buffer, Buffer, Buffer>;
  pin_hash: ColumnType<Buffer, Buffer, Buffer>;
  pin_iterations: number;
  revoked_at: ColumnType<Date | null, never, Date>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export interface DevicesTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  name: ColumnType<string, string, string>;
  paired_at: CreatedAt;
  last_renewed_at: ColumnType<Date, never, Date>;
  last_renewal_issued_at: ColumnType<Date | null, never, Date>;
  last_seen_at: ColumnType<Date, never, Date>;
  revoked_at: ColumnType<Date | null, never, Date | null>;
  created_at: CreatedAt;
}

/** An ECDSA P-256 public key as a JWK. */
export interface DevicePublicKey {
  kty: "EC";
  crv: "P-256";
  x: string;
  y: string;
}

export interface DeviceKeysTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  device_id: ColumnType<string, string, never>;
  public_key: ColumnType<DevicePublicKey, string, never>;
  /** Set when the device paired again with a newer key; only the key with none renews tokens. */
  retired_at: ColumnType<Date | null, never, Date>;
  /** Set when the device was revoked while this key was its own; events it signed are held for review. */
  revoked_at: ColumnType<Date | null, never, Date>;
  created_at: CreatedAt;
}

export interface DeviceTokensTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  device_id: ColumnType<string, string, never>;
  token_hash: TokenHash;
  expires_at: ColumnType<Date, Date, never>;
  created_at: CreatedAt;
}

export interface PairingCodesTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  owner_id: ColumnType<string, string, never>;
  device_name: ColumnType<string, string, never>;
  lookup_hash: TokenHash;
  secret_hash: TokenHash;
  failed_attempts: ColumnType<number, never, number>;
  expires_at: ColumnType<Date, Date, never>;
  created_at: CreatedAt;
}

/** A phone number: no café of its own, reachable through a café's cards (AC 3). Never updated. */
export interface CustomersTable {
  id: ColumnType<string, string | undefined, never>;
  /** HMAC-SHA256 of the E.164 number with the server's pepper. */
  phone_lookup: ColumnType<Buffer, Buffer, never>;
  /** AES-256-GCM: IV, tag, ciphertext. */
  phone_ciphertext: ColumnType<Buffer, Buffer, never>;
  phone_key_id: ColumnType<string, string, never>;
  created_at: CreatedAt;
}

export interface CardsTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  /** Null for a card that is not linked to a phone number (the number already had a card at this café). */
  customer_id: ColumnType<string | null, string | null | undefined, never>;
  epoch: ColumnType<number, never, number>;
  web_secret_hash: ColumnType<Buffer, Buffer, Buffer>;
  stamps: ColumnType<number, never, number>;
  privacy_accepted_at: ColumnType<Date, Date, never>;
  offers_opt_in_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
  email: ColumnType<string | null, never, string | null>;
  email_lookup: ColumnType<Buffer | null, never, Buffer | null>;
  /** When the card was first scanned at a counter: only then may it be stamped by phone number. */
  phone_confirmed_at: ColumnType<Date | null, never, Date>;
  /** When another card here signed up with the same number: from then on this card is never stamped by number. */
  phone_disputed_at: ColumnType<Date | null, never, Date>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type SyncEventStatus = "applied" | "held" | "discarded" | "rejected";
export type SyncHoldReason = "device_revoked" | "staff_revoked" | "late_sync";

/** The ledger of synced events (AC 24): no payload, no personal data. Only a held event's review is updated. */
export interface SyncEventsTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  device_id: ColumnType<string, string, never>;
  event_id: ColumnType<string, string, never>;
  payload_hash: ColumnType<Buffer, Buffer, never>;
  key_id: ColumnType<string, string, never>;
  staff_id: ColumnType<string, string, never>;
  type: ColumnType<string, string, never>;
  schema_version: ColumnType<number, number, never>;
  sequence: ColumnType<number, number, never>;
  occurred_at: ColumnType<Date, Date, never>;
  received_at: CreatedAt;
  status: ColumnType<SyncEventStatus, SyncEventStatus, SyncEventStatus>;
  hold_reason: ColumnType<SyncHoldReason | null, SyncHoldReason | null | undefined, never>;
  reviewed_at: ColumnType<Date | null, never, Date>;
  reviewed_by: ColumnType<string | null, never, string>;
  /** The refusal code of a rejected event, sent again to a device that resends it. */
  result_code: ColumnType<string | null, string | null | undefined, never>;
}

export type VisitOutcome = "held" | "discarded" | "stamped" | "no_stamps" | "cooldown" | "daily_cap" | "card_gone";

/** A synced visit (Step 9). Never deleted; card_id is set null when the card is deleted (AC 9). */
export interface VisitsTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  sync_event_id: ColumnType<string, string, never>;
  card_id: ColumnType<string | null, string | null, never>;
  identified_by: ColumnType<"qr" | "phone", "qr" | "phone", never>;
  device_id: ColumnType<string, string, never>;
  staff_id: ColumnType<string, string, never>;
  occurred_at: ColumnType<Date, Date, never>;
  total_cents: ColumnType<number, number, never>;
  stamps_earned: ColumnType<number, number, never>;
  stamps_added: ColumnType<number, number | undefined, number>;
  outcome: ColumnType<VisitOutcome, VisitOutcome, VisitOutcome>;
  created_at: CreatedAt;
}

/** A visit's lines, priced as the counter saw them (AC 32). Append-only. */
export interface VisitItemsTable {
  cafe_id: ColumnType<string, string, never>;
  visit_id: ColumnType<string, string, never>;
  line: ColumnType<number, number, never>;
  order_type_id: ColumnType<string, string, never>;
  quantity: ColumnType<number, number, never>;
  unit_price_cents: ColumnType<number, number, never>;
  unit_cost_cents: ColumnType<number, number, never>;
  catalog_version: ColumnType<number, number, never>;
  stamps_each: ColumnType<number, number, never>;
}

/** A reward given at the counter (AC 31). Append-only; card_id is set null when the card is deleted. */
export interface RedemptionsTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  device_id: ColumnType<string, string, never>;
  event_id: ColumnType<string, string, never>;
  card_id: ColumnType<string | null, string, never>;
  staff_id: ColumnType<string, string, never>;
  stamps_used: ColumnType<number, number, never>;
  stamps_left: ColumnType<number, number, never>;
  redeemed_at: CreatedAt;
}

/** A card's Apple Wallet pass at one epoch (Step 10); the id is its serial number. Deleted with the card. */
export interface ApplePassesTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  card_id: ColumnType<string, string, never>;
  epoch: ColumnType<number, number, never>;
  /** SHA-256 of the pass's authenticationToken. */
  auth_token_hash: ColumnType<Buffer, Buffer, never>;
  layout_version: ColumnType<number, number, number>;
  /** The transaction that last changed the pass (xid8, as a decimal string): the web service's lastUpdated tag. */
  updated_xid: ColumnType<string, never, string>;
  /** Last-Modified, in whole seconds, later by at least a second on every change. */
  modified_at: ColumnType<Date, never, Date>;
  /** The change (updated_xid) the last successful push delivered; the worker's sweep pushes again when it lags. */
  delivered_xid: ColumnType<string | null, never, string | null>;
  /** Failed pushes in a row, the last one's time and error code (never personal data); reset by a push that succeeds. */
  delivery_failures: ColumnType<number, never, number>;
  delivery_failed_at: ColumnType<Date | null, never, Date | null>;
  delivery_error: ColumnType<string | null, never, string | null>;
  created_at: CreatedAt;
}

/** A card's Google Wallet loyalty object at one epoch (Step 10); deleted with the card. */
export interface GooglePassesTable {
  id: ColumnType<string, string | undefined, never>;
  cafe_id: ColumnType<string, string, never>;
  card_id: ColumnType<string, string, never>;
  epoch: ColumnType<number, number, never>;
  /** The transaction that last changed the pass (xid8, as a decimal string). */
  updated_xid: ColumnType<string, never, string>;
  /** The change the last successful write delivered; the worker's sweep writes the pass again when it lags. */
  delivered_xid: ColumnType<string | null, never, string | null>;
  /** Failed writes to Google in a row, the last one's time and error code; reset by a write that succeeds. */
  delivery_failures: ColumnType<number, never, number>;
  delivery_failed_at: ColumnType<Date | null, never, Date | null>;
  delivery_error: ColumnType<string | null, never, string | null>;
  created_at: CreatedAt;
}

/** A device registered for a pass's updates. */
export interface ApplePassRegistrationsTable {
  cafe_id: ColumnType<string, string, never>;
  pass_id: ColumnType<string, string, never>;
  /** SHA-256 of the device library identifier. */
  device_library_hash: ColumnType<Buffer, Buffer, never>;
  push_token: ColumnType<string, string, string>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export interface CustomerRecoveryTokensTable {
  id: ColumnType<string, string | undefined, never>;
  /** HMAC of the email the link was sent to; one link per email. */
  email_lookup: ColumnType<Buffer, Buffer, never>;
  token_hash: ColumnType<Buffer, Buffer, Buffer>;
  expires_at: ColumnType<Date, Date, Date>;
  created_at: CreatedAt;
}

/**
 * Tables in schema `app`, as the app role sees them. Every one is scoped to a café by row-level security; owners,
 * invites, sessions, reset tokens, pairing codes, device tokens and device keys can also be read (never written) by
 * their email, token hash or key id (withLookup).
 */
export interface Database {
  cafes: CafesTable;
  loyalty_programs: LoyaltyProgramsTable;
  order_types: OrderTypesTable;
  audit_log: AuditLogTable;
  owners: OwnersTable;
  owner_invites: OwnerInvitesTable;
  owner_sessions: OwnerSessionsTable;
  password_reset_tokens: PasswordResetTokensTable;
  staff: StaffTable;
  devices: DevicesTable;
  device_keys: DeviceKeysTable;
  device_tokens: DeviceTokensTable;
  pairing_codes: PairingCodesTable;
  customers: CustomersTable;
  cards: CardsTable;
  customer_recovery_tokens: CustomerRecoveryTokensTable;
  sync_events: SyncEventsTable;
  visits: VisitsTable;
  visit_items: VisitItemsTable;
  redemptions: RedemptionsTable;
  apple_passes: ApplePassesTable;
  apple_pass_registrations: ApplePassRegistrationsTable;
  google_passes: GooglePassesTable;
}

export type TableName = keyof Database;

type ColumnLists = { readonly [T in TableName]: readonly (keyof Database[T] & string)[] };

/** Every column of every table, checked against the live schema by an integration test. */
export const TABLE_COLUMNS = {
  cafes: ["id", "name", "time_zone", "catalog_version", "join_code", "join_code_hash", "created_at", "updated_at"],
  loyalty_programs: ["id", "cafe_id", "stamps_required", "reward_name_ar", "reward_name_en", "created_at", "updated_at"],
  order_types: [
    "id",
    "cafe_id",
    "name_ar",
    "name_en",
    "price_cents",
    "cost_cents",
    "stamps_earned",
    "active",
    "sort_order",
    "created_at",
    "updated_at",
  ],
  audit_log: ["id", "cafe_id", "actor_type", "actor_id", "action", "entity_type", "entity_id", "changes", "occurred_at"],
  owners: ["id", "cafe_id", "email", "password_hash", "password_changed_at", "created_at", "updated_at"],
  owner_invites: ["id", "cafe_id", "token_hash", "expires_at", "used_at", "created_at"],
  owner_sessions: ["id", "cafe_id", "owner_id", "token_hash", "created_at", "last_seen_at", "expires_at"],
  password_reset_tokens: ["id", "cafe_id", "owner_id", "token_hash", "expires_at", "created_at"],
  staff: ["id", "cafe_id", "name", "pin_salt", "pin_hash", "pin_iterations", "revoked_at", "created_at", "updated_at"],
  devices: ["id", "cafe_id", "name", "paired_at", "last_renewed_at", "last_renewal_issued_at", "last_seen_at", "revoked_at", "created_at"],
  device_keys: ["id", "cafe_id", "device_id", "public_key", "retired_at", "revoked_at", "created_at"],
  device_tokens: ["id", "cafe_id", "device_id", "token_hash", "expires_at", "created_at"],
  pairing_codes: ["id", "cafe_id", "owner_id", "device_name", "lookup_hash", "secret_hash", "failed_attempts", "expires_at", "created_at"],
  customers: ["id", "phone_lookup", "phone_ciphertext", "phone_key_id", "created_at"],
  cards: [
    "id",
    "cafe_id",
    "customer_id",
    "epoch",
    "web_secret_hash",
    "stamps",
    "privacy_accepted_at",
    "offers_opt_in_at",
    "email",
    "email_lookup",
    "phone_confirmed_at",
    "phone_disputed_at",
    "created_at",
    "updated_at",
  ],
  customer_recovery_tokens: ["id", "email_lookup", "token_hash", "expires_at", "created_at"],
  sync_events: [
    "id",
    "cafe_id",
    "device_id",
    "event_id",
    "payload_hash",
    "key_id",
    "staff_id",
    "type",
    "schema_version",
    "sequence",
    "occurred_at",
    "received_at",
    "status",
    "hold_reason",
    "reviewed_at",
    "reviewed_by",
    "result_code",
  ],
  visits: [
    "id",
    "cafe_id",
    "sync_event_id",
    "card_id",
    "identified_by",
    "device_id",
    "staff_id",
    "occurred_at",
    "total_cents",
    "stamps_earned",
    "stamps_added",
    "outcome",
    "created_at",
  ],
  visit_items: ["cafe_id", "visit_id", "line", "order_type_id", "quantity", "unit_price_cents", "unit_cost_cents", "catalog_version", "stamps_each"],
  redemptions: ["id", "cafe_id", "device_id", "event_id", "card_id", "staff_id", "stamps_used", "stamps_left", "redeemed_at"],
  apple_passes: [
    "id",
    "cafe_id",
    "card_id",
    "epoch",
    "auth_token_hash",
    "layout_version",
    "updated_xid",
    "modified_at",
    "delivered_xid",
    "delivery_failures",
    "delivery_failed_at",
    "delivery_error",
    "created_at",
  ],
  apple_pass_registrations: ["cafe_id", "pass_id", "device_library_hash", "push_token", "created_at", "updated_at"],
  google_passes: ["id", "cafe_id", "card_id", "epoch", "updated_xid", "delivered_xid", "delivery_failures", "delivery_failed_at", "delivery_error", "created_at"],
} as const satisfies ColumnLists;

/**
 * The column holding each table's café: `id` for cafes itself, `cafe_id` for café tables, null for the two global
 * tables (customers, reached only through cards, and customer recovery tokens), which have their own tests.
 */
export const TENANT_KEY: Readonly<Record<TableName, "id" | "cafe_id" | null>> = {
  cafes: "id",
  loyalty_programs: "cafe_id",
  order_types: "cafe_id",
  audit_log: "cafe_id",
  owners: "cafe_id",
  owner_invites: "cafe_id",
  owner_sessions: "cafe_id",
  password_reset_tokens: "cafe_id",
  staff: "cafe_id",
  devices: "cafe_id",
  device_keys: "cafe_id",
  device_tokens: "cafe_id",
  pairing_codes: "cafe_id",
  cards: "cafe_id",
  customers: null,
  customer_recovery_tokens: null,
  sync_events: "cafe_id",
  visits: "cafe_id",
  visit_items: "cafe_id",
  redemptions: "cafe_id",
  apple_passes: "cafe_id",
  apple_pass_registrations: "cafe_id",
  google_passes: "cafe_id",
};

type ListedColumns = { [T in TableName]: (typeof TABLE_COLUMNS)[T][number] };
type CompletenessByTable = { [T in TableName]: [Exclude<keyof Database[T], ListedColumns[T]>] extends [never] ? true : false };
type AssertAllTrue<X extends Record<TableName, true>> = X;
/** Compile-time check that TABLE_COLUMNS lists every column of the Database interface; fails to compile otherwise. */
export type TableColumnsAreComplete = AssertAllTrue<CompletenessByTable>;
